Repository PipeMasters/frontend, pull requests merged in 2025-07, with the labels that each got.

#8 Feature/overview
  src/routes/index.tsx
  src/routes/overview/$fileId.tsx
  src/widgets/uploadFileForm.tsx
Labels: enhancement

#14 Feature/overview component
  src/routes/overview/$fileId.tsx
  src/services/file/model.ts
  src/widgets/uploadFileForm.tsx
Labels: bug, enhancement

#15 Feature/filter batch
  src/features/batch/index.ts
  src/features/batch/useBatches.tsx
  src/routes/index.tsx
  src/services/batch/batchServices.ts
  src/services/batch/model.ts
  src/services/train/model.ts
  src/widgets/batchVideo.tsx
  src/widgets/filterCard.tsx
Labels: enhancement

#16 Feature/user
  src/features/delegat/index.ts
  src/features/delegat/useCreateDelegation.tsx
  src/features/user/index.ts
  src/features/user/useCreateUser.tsx
  src/features/user/useGetUsers.tsx
  src/routes/index.tsx
  src/routes/overview/$fileId.tsx
  src/services/delegat/delegatService.ts
  src/services/delegat/index.ts
  src/services/delegat/model.ts
  src/services/train/model.ts
  src/services/user/model.ts
  src/services/user/userService.ts
  src/widgets/createBatchForm.tsx
  src/widgets/createDelegateForm.tsx
  src/widgets/createUserForm.tsx
  src/widgets/filterCard.tsx
  src/widgets/modalButton.tsx
Labels: enhancement

#17 Feature/zustand
  index.html
  package-lock.json
  package.json
  public/favicon.ico
  src/services/file/fileService.ts
  src/store/filterStore.ts
  src/widgets/filterCard.tsx
Labels: bug, enhancement

#22 hotfix
  src/routes/home.tsx
  src/routes/index.tsx
  src/services/train/model.ts
  src/utils/validExtensions.ts
Labels: bug

#24 Feature/transcription
  src/features/transcripts/useGetMediaTranscript.tsx
  src/features/transcripts/useGetTranscript.tsx
  src/routes/home.tsx
  src/routes/overview/$fileId.tsx
  src/services/transcripts/model.ts
  src/widgets/metricsDashboard.tsx
  src/widgets/searchInput.tsx
  src/widgets/searchResults.tsx
  src/widgets/uploadFileForm.tsx
Labels: enhancement

#25 fix: delete unused
  package-lock.json
  package.json
Labels: bug

#28 Fix/search res
  src/routes/home.tsx
  src/routes/overview/$fileId.tsx
  src/services/batch/model.ts
  src/services/file/model.ts
  src/widgets/batchVideo.tsx
  src/widgets/searchResults.tsx
Labels: bug

#29 Create test-pr.yml
  .github/workflows/test-pr.yml
Labels: bug

#33 Feature/fix adaptive
  package-lock.json
  src/features/tag/index.ts
  src/features/tag/useGetTags.tsx
  src/features/train/useGetChiefs.tsx
  src/routes/home.tsx
  src/services/batch/batchServices.ts
  src/services/batch/model.ts
  src/services/tag/index.ts
  src/services/tag/model.ts
  src/services/tag/tagService.ts
  src/services/train/trainService.ts
  src/widgets/batchVideo.tsx
  src/widgets/filterCard.tsx
  src/widgets/metricsDashboard.tsx
  src/widgets/searchInput.tsx
Labels: enhancement

#34 Feature/tag filter
  src/widgets/createTrainForm.tsx
  src/widgets/filterCard.tsx
Labels: enhancement

#35 fix: adaptive
  src/widgets/searchInput.tsx
Labels: bug
